kaspad_address: "127.0.0.1:16110"
block_wait_time: 1000
print_stats: true
log_to_file: true
health_check_port: ""
var_diff: true
var_diff_stats: true
pow2_clamp: true
extranonce_size: 2
instances:
  # Instance 1: Low difficulty pool (for smaller miners or testing)
  - stratum_port: ":5553"
    min_share_diff: 4096
    prom_port: ":2114"
    log_to_file: true
    shares_per_min: 30

  # Instance 2: Medium difficulty pool
  - stratum_port: ":5554"
    min_share_diff: 4096
    prom_port: ":2115"
    log_to_file: true
    shares_per_min: 30

  # Instance 3: High difficulty pool (for powerful miners)
  - stratum_port: ":5555"
    min_share_diff: 4096
    prom_port: ":2116"
    log_to_file: true
    shares_per_min: 30

  # Instance 4: Very high difficulty pool (for very powerful miners)
  - stratum_port: ":5556"
    min_share_diff: 4096
    prom_port: ":2117"
    log_to_file: true
<<<<<<< HEAD
    shares_per_min: 30

  # Instance 5: Very high difficulty pool (for very powerful miners)
  - stratum_port: ":5557"
    min_share_diff: 4096
    prom_port: ":2118"
    log_to_file: true
    shares_per_min: 30

  # Instance 6: Very high difficulty pool (for very powerful miners)
  - stratum_port: ":5558"
    min_share_diff: 4096
    prom_port: ":2119"
    log_to_file: true
    shares_per_min: 30
=======
    # Optional: instance-specific overrides
    # var_diff: true
    # shares_per_min: 30
>>>>>>> livelaugh/BridgeBinary
